{
    "SAVER_PUBKEY": {
        "value": "0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
        "type": "u256"
    },
    "BROKER_PUBKEY": {
        "value": "0xc6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
        "type": "u256"
    },
    "KEEPER_PUBKEY": {
        "value": "0xf9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9",
        "type": "u256"
    },
    "BROKER_FEE_BP": {
        "value": "250",
        "type": "u32"
    },
    "URGENT_FEE": {
        "value": "5000",
        "type": "u64"
    },
    "PLANNED_TIMELOCK": {
        "value": "10080",
        "type": "u32"
    },
    "URGENT_TIMELOCK": {
        "value": "1440",
        "type": "u32"
    },
    "KEY_RECOVERY_TIMELOCK": {
        "value": "43200",
        "type": "u32"
    },
    "PARAMS_CHANGE_TIMELOCK": {
        "value": "20160",
        "type": "u32"
    }
}
